# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v2/intellidocs_v2.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'v2/intellidocs_v2.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17v2/intellidocs_v2.proto\x12\x14intellidocs_proto.v2\"\'\n\x12ProcessPDFsRequest\x12\x11\n\tpdf_paths\x18\x01 \x03(\t\"\x8f\x01\n\x13ProcessPDFsResponse\x12H\n\x08pdf_keys\x18\x01 \x03(\x0b\x32\x36.intellidocs_proto.v2.ProcessPDFsResponse.PdfKeysEntry\x1a.\n\x0cPdfKeysEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"J\n\x14QueryDocumentRequest\x12\x0f\n\x07pdf_key\x18\x01 \x01(\t\x12\x12\n\nuser_query\x18\x02 \x01(\t\x12\r\n\x05top_n\x18\x03 \x01(\x05\"\x8e\x01\n\x15QueryDocumentResponse\x12H\n\x07results\x18\x01 \x03(\x0b\x32\x37.intellidocs_proto.v2.QueryDocumentResponse.QueryResult\x1a+\n\x0bQueryResult\x12\r\n\x05\x63hunk\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x32\xe2\x01\n\x12IntellidocsService\x12\x62\n\x0bProcessPDFs\x12(.intellidocs_proto.v2.ProcessPDFsRequest\x1a).intellidocs_proto.v2.ProcessPDFsResponse\x12h\n\rQueryDocument\x12*.intellidocs_proto.v2.QueryDocumentRequest\x1a+.intellidocs_proto.v2.QueryDocumentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v2.intellidocs_v2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSPDFSRESPONSE_PDFKEYSENTRY']._loaded_options = None
  _globals['_PROCESSPDFSRESPONSE_PDFKEYSENTRY']._serialized_options = b'8\001'
  _globals['_PROCESSPDFSREQUEST']._serialized_start=49
  _globals['_PROCESSPDFSREQUEST']._serialized_end=88
  _globals['_PROCESSPDFSRESPONSE']._serialized_start=91
  _globals['_PROCESSPDFSRESPONSE']._serialized_end=234
  _globals['_PROCESSPDFSRESPONSE_PDFKEYSENTRY']._serialized_start=188
  _globals['_PROCESSPDFSRESPONSE_PDFKEYSENTRY']._serialized_end=234
  _globals['_QUERYDOCUMENTREQUEST']._serialized_start=236
  _globals['_QUERYDOCUMENTREQUEST']._serialized_end=310
  _globals['_QUERYDOCUMENTRESPONSE']._serialized_start=313
  _globals['_QUERYDOCUMENTRESPONSE']._serialized_end=455
  _globals['_QUERYDOCUMENTRESPONSE_QUERYRESULT']._serialized_start=412
  _globals['_QUERYDOCUMENTRESPONSE_QUERYRESULT']._serialized_end=455
  _globals['_INTELLIDOCSSERVICE']._serialized_start=458
  _globals['_INTELLIDOCSSERVICE']._serialized_end=684
# @@protoc_insertion_point(module_scope)
