# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/intellidocs.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 27, 2, "", "v1/intellidocs.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14v1/intellidocs.proto\x12\x14intellidocs_proto.v1"B\n\x17\x43hatWithDocumentRequest\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x12\n\nuser_query\x18\x02 \x01(\t"2\n\x18\x43hatWithDocumentResponse\x12\x16\n\x0equery_response\x18\x01 \x03(\t2\x8b\x01\n\x12IntelliDocsService\x12u\n\x10\x43hatWithDocument\x12-.intellidocs_proto.v1.ChatWithDocumentRequest\x1a..intellidocs_proto.v1.ChatWithDocumentResponse(\x01\x30\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "v1.intellidocs_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CHATWITHDOCUMENTREQUEST"]._serialized_start = 46
    _globals["_CHATWITHDOCUMENTREQUEST"]._serialized_end = 112
    _globals["_CHATWITHDOCUMENTRESPONSE"]._serialized_start = 114
    _globals["_CHATWITHDOCUMENTRESPONSE"]._serialized_end = 164
    _globals["_INTELLIDOCSSERVICE"]._serialized_start = 167
    _globals["_INTELLIDOCSSERVICE"]._serialized_end = 306
# @@protoc_insertion_point(module_scope)
