# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: intellidocs.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'intellidocs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11intellidocs.proto\x12\x0bintellidocs\"0\n\x16ProcessDocumentRequest\x12\x16\n\x0e\x64ocument_paths\x18\x01 \x03(\t\"*\n\x17ProcessDocumentResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"I\n\x13RetrieveTopNRequest\x12\x12\n\nuser_query\x18\x01 \x01(\t\x12\x0f\n\x07\x64oc_key\x18\x02 \x01(\t\x12\r\n\x05top_n\x18\x03 \x01(\x05\"D\n\x14RetrieveTopNResponse\x12,\n\x06\x63hunks\x18\x01 \x03(\x0b\x32\x1c.intellidocs.RetrievedChunks\"0\n\x0fRetrievedChunks\x12\x0e\n\x06\x63hunks\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x32\xc8\x01\n\x12IntelliDocsService\x12]\n\x10ProcessDocuments\x12#.intellidocs.ProcessDocumentRequest\x1a$.intellidocs.ProcessDocumentResponse\x12S\n\x0cRetrieveTopN\x12 .intellidocs.RetrieveTopNRequest\x1a!.intellidocs.RetrieveTopNResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'intellidocs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSDOCUMENTREQUEST']._serialized_start=34
  _globals['_PROCESSDOCUMENTREQUEST']._serialized_end=82
  _globals['_PROCESSDOCUMENTRESPONSE']._serialized_start=84
  _globals['_PROCESSDOCUMENTRESPONSE']._serialized_end=126
  _globals['_RETRIEVETOPNREQUEST']._serialized_start=128
  _globals['_RETRIEVETOPNREQUEST']._serialized_end=201
  _globals['_RETRIEVETOPNRESPONSE']._serialized_start=203
  _globals['_RETRIEVETOPNRESPONSE']._serialized_end=271
  _globals['_RETRIEVEDCHUNKS']._serialized_start=273
  _globals['_RETRIEVEDCHUNKS']._serialized_end=321
  _globals['_INTELLIDOCSSERVICE']._serialized_start=324
  _globals['_INTELLIDOCSSERVICE']._serialized_end=524
# @@protoc_insertion_point(module_scope)
