# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import intellidocs_pb2 as intellidocs__pb2


GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in intellidocs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IntelliDocsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessDocuments = channel.unary_unary(
                '/intellidocs.IntelliDocsService/ProcessDocuments',
                request_serializer=intellidocs__pb2.ProcessDocumentRequest.SerializeToString,
                response_deserializer=intellidocs__pb2.ProcessDocumentResponse.FromString,
                _registered_method=True)
        self.RetrieveTopN = channel.unary_unary(
                '/intellidocs.IntelliDocsService/RetrieveTopN',
                request_serializer=intellidocs__pb2.RetrieveTopNRequest.SerializeToString,
                response_deserializer=intellidocs__pb2.RetrieveTopNResponse.FromString,
                _registered_method=True)


class IntelliDocsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveTopN(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntelliDocsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessDocuments,
                    request_deserializer=intellidocs__pb2.ProcessDocumentRequest.FromString,
                    response_serializer=intellidocs__pb2.ProcessDocumentResponse.SerializeToString,
            ),
            'RetrieveTopN': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveTopN,
                    request_deserializer=intellidocs__pb2.RetrieveTopNRequest.FromString,
                    response_serializer=intellidocs__pb2.RetrieveTopNResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'intellidocs.IntelliDocsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('intellidocs.IntelliDocsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IntelliDocsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/intellidocs.IntelliDocsService/ProcessDocuments',
            intellidocs__pb2.ProcessDocumentRequest.SerializeToString,
            intellidocs__pb2.ProcessDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveTopN(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/intellidocs.IntelliDocsService/RetrieveTopN',
            intellidocs__pb2.RetrieveTopNRequest.SerializeToString,
            intellidocs__pb2.RetrieveTopNResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
