# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from v1 import intellidocs_pb2 as v1_dot_intellidocs__pb2

GRPC_GENERATED_VERSION = '1.66.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in v1/intellidocs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IntelliDocsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatWithDocument = channel.stream_stream(
                '/intellidocs_proto.v1.IntelliDocsService/ChatWithDocument',
                request_serializer=v1_dot_intellidocs__pb2.ChatWithDocumentRequest.SerializeToString,
                response_deserializer=v1_dot_intellidocs__pb2.ChatWithDocumentResponse.FromString,
                _registered_method=True)


class IntelliDocsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ChatWithDocument(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntelliDocsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatWithDocument': grpc.stream_stream_rpc_method_handler(
                    servicer.ChatWithDocument,
                    request_deserializer=v1_dot_intellidocs__pb2.ChatWithDocumentRequest.FromString,
                    response_serializer=v1_dot_intellidocs__pb2.ChatWithDocumentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'intellidocs_proto.v1.IntelliDocsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('intellidocs_proto.v1.IntelliDocsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IntelliDocsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ChatWithDocument(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/intellidocs_proto.v1.IntelliDocsService/ChatWithDocument',
            v1_dot_intellidocs__pb2.ChatWithDocumentRequest.SerializeToString,
            v1_dot_intellidocs__pb2.ChatWithDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
