// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/intellidocs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentPaths []string               `protobuf:"bytes,1,rep,name=document_paths,json=documentPaths,proto3" json:"document_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessDocumentRequest) Reset() {
	*x = ProcessDocumentRequest{}
	mi := &file_proto_intellidocs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDocumentRequest) ProtoMessage() {}

func (x *ProcessDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_intellidocs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDocumentRequest.ProtoReflect.Descriptor instead.
func (*ProcessDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_intellidocs_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessDocumentRequest) GetDocumentPaths() []string {
	if x != nil {
		return x.DocumentPaths
	}
	return nil
}

type ProcessDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessDocumentResponse) Reset() {
	*x = ProcessDocumentResponse{}
	mi := &file_proto_intellidocs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDocumentResponse) ProtoMessage() {}

func (x *ProcessDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_intellidocs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDocumentResponse.ProtoReflect.Descriptor instead.
func (*ProcessDocumentResponse) Descriptor() ([]byte, []int) {
	return file_proto_intellidocs_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessDocumentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RetrieveTopNRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserQuery     string                 `protobuf:"bytes,1,opt,name=user_query,json=userQuery,proto3" json:"user_query,omitempty"`
	DocKey        string                 `protobuf:"bytes,2,opt,name=doc_key,json=docKey,proto3" json:"doc_key,omitempty"`
	TopN          int32                  `protobuf:"varint,3,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveTopNRequest) Reset() {
	*x = RetrieveTopNRequest{}
	mi := &file_proto_intellidocs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveTopNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveTopNRequest) ProtoMessage() {}

func (x *RetrieveTopNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_intellidocs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveTopNRequest.ProtoReflect.Descriptor instead.
func (*RetrieveTopNRequest) Descriptor() ([]byte, []int) {
	return file_proto_intellidocs_proto_rawDescGZIP(), []int{2}
}

func (x *RetrieveTopNRequest) GetUserQuery() string {
	if x != nil {
		return x.UserQuery
	}
	return ""
}

func (x *RetrieveTopNRequest) GetDocKey() string {
	if x != nil {
		return x.DocKey
	}
	return ""
}

func (x *RetrieveTopNRequest) GetTopN() int32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

type RetrieveTopNResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*RetrievedChunks     `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveTopNResponse) Reset() {
	*x = RetrieveTopNResponse{}
	mi := &file_proto_intellidocs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveTopNResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveTopNResponse) ProtoMessage() {}

func (x *RetrieveTopNResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_intellidocs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveTopNResponse.ProtoReflect.Descriptor instead.
func (*RetrieveTopNResponse) Descriptor() ([]byte, []int) {
	return file_proto_intellidocs_proto_rawDescGZIP(), []int{3}
}

func (x *RetrieveTopNResponse) GetChunks() []*RetrievedChunks {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type RetrievedChunks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        string                 `protobuf:"bytes,1,opt,name=chunks,proto3" json:"chunks,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrievedChunks) Reset() {
	*x = RetrievedChunks{}
	mi := &file_proto_intellidocs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievedChunks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievedChunks) ProtoMessage() {}

func (x *RetrievedChunks) ProtoReflect() protoreflect.Message {
	mi := &file_proto_intellidocs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievedChunks.ProtoReflect.Descriptor instead.
func (*RetrievedChunks) Descriptor() ([]byte, []int) {
	return file_proto_intellidocs_proto_rawDescGZIP(), []int{4}
}

func (x *RetrievedChunks) GetChunks() string {
	if x != nil {
		return x.Chunks
	}
	return ""
}

func (x *RetrievedChunks) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_proto_intellidocs_proto protoreflect.FileDescriptor

const file_proto_intellidocs_proto_rawDesc = "" +
	"\n" +
	"\x17proto/intellidocs.proto\x12\vintellidocs\"?\n" +
	"\x16ProcessDocumentRequest\x12%\n" +
	"\x0edocument_paths\x18\x01 \x03(\tR\rdocumentPaths\"3\n" +
	"\x17ProcessDocumentResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"b\n" +
	"\x13RetrieveTopNRequest\x12\x1d\n" +
	"\n" +
	"user_query\x18\x01 \x01(\tR\tuserQuery\x12\x17\n" +
	"\adoc_key\x18\x02 \x01(\tR\x06docKey\x12\x13\n" +
	"\x05top_n\x18\x03 \x01(\x05R\x04topN\"L\n" +
	"\x14RetrieveTopNResponse\x124\n" +
	"\x06chunks\x18\x01 \x03(\v2\x1c.intellidocs.RetrievedChunksR\x06chunks\"?\n" +
	"\x0fRetrievedChunks\x12\x16\n" +
	"\x06chunks\x18\x01 \x01(\tR\x06chunks\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score2\xc8\x01\n" +
	"\x12IntelliDocsService\x12]\n" +
	"\x10ProcessDocuments\x12#.intellidocs.ProcessDocumentRequest\x1a$.intellidocs.ProcessDocumentResponse\x12S\n" +
	"\fRetrieveTopN\x12 .intellidocs.RetrieveTopNRequest\x1a!.intellidocs.RetrieveTopNResponseB/Z-github.com/anishka07/intellidocs-client/protob\x06proto3"

var (
	file_proto_intellidocs_proto_rawDescOnce sync.Once
	file_proto_intellidocs_proto_rawDescData []byte
)

func file_proto_intellidocs_proto_rawDescGZIP() []byte {
	file_proto_intellidocs_proto_rawDescOnce.Do(func() {
		file_proto_intellidocs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_intellidocs_proto_rawDesc), len(file_proto_intellidocs_proto_rawDesc)))
	})
	return file_proto_intellidocs_proto_rawDescData
}

var file_proto_intellidocs_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_intellidocs_proto_goTypes = []any{
	(*ProcessDocumentRequest)(nil),  // 0: intellidocs.ProcessDocumentRequest
	(*ProcessDocumentResponse)(nil), // 1: intellidocs.ProcessDocumentResponse
	(*RetrieveTopNRequest)(nil),     // 2: intellidocs.RetrieveTopNRequest
	(*RetrieveTopNResponse)(nil),    // 3: intellidocs.RetrieveTopNResponse
	(*RetrievedChunks)(nil),         // 4: intellidocs.RetrievedChunks
}
var file_proto_intellidocs_proto_depIdxs = []int32{
	4, // 0: intellidocs.RetrieveTopNResponse.chunks:type_name -> intellidocs.RetrievedChunks
	0, // 1: intellidocs.IntelliDocsService.ProcessDocuments:input_type -> intellidocs.ProcessDocumentRequest
	2, // 2: intellidocs.IntelliDocsService.RetrieveTopN:input_type -> intellidocs.RetrieveTopNRequest
	1, // 3: intellidocs.IntelliDocsService.ProcessDocuments:output_type -> intellidocs.ProcessDocumentResponse
	3, // 4: intellidocs.IntelliDocsService.RetrieveTopN:output_type -> intellidocs.RetrieveTopNResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_intellidocs_proto_init() }
func file_proto_intellidocs_proto_init() {
	if File_proto_intellidocs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_intellidocs_proto_rawDesc), len(file_proto_intellidocs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_intellidocs_proto_goTypes,
		DependencyIndexes: file_proto_intellidocs_proto_depIdxs,
		MessageInfos:      file_proto_intellidocs_proto_msgTypes,
	}.Build()
	File_proto_intellidocs_proto = out.File
	file_proto_intellidocs_proto_goTypes = nil
	file_proto_intellidocs_proto_depIdxs = nil
}
